### PR TITLE
Change units manage page

### PR DESCRIPTION
**Pull request by twinser**
Not entirely pleased with the spacing on the "Space Used (KB)" column. Would be nicer if it wasn't as wide, but was struggling to thin it...

### CODE REVIEW

**Comment by erowan** [comment]
I think the original gripe about displaying the space used for a scenario in readable units (i.e. bytes, KB, MB etc) was that it was difficult to sort the data. It's probably about time we made the stubs table sortable on the different columns. We could have use the readable units displayed again and provide a function to sort them correctly. There are a few jquery table sorters.

**Comment by johnecobo** [comment]
Sorting on table columns is a "nice to have" in my opinion. Having the units consistent is an improvement as is as now one can scroll up and down to easily scan sizes.

**Comment by erowan** [comment]
twinser can you move the styling to the stubo.css

**Comment by twinser** [comment]
@erowan I have actually been working on sorting the table on another branch. I ran into problems because of the way the scenario can have more than one session in the table. I would need to do some more work on it, but can if you like. 

Will move the styling now.

**Pull request merged**
