### PR TITLE
Feature/commands export

### PR DESCRIPTION
**Pull request by rusenask**
Bringing back support for .commands format. Integrating both formats together. New '.yaml' format files will reside under '/yaml_format' sub directory under each scenario exported files.

closes https://github.com/Stub-O-Matic/stubo-app/issues/63

### CODE REVIEW

**Comment by erowan** [comment]
Can you change this to only export one format with yaml being the default. Add an url argument that would specify format type to enable the legacy .commands to be exported. I don't see the point of exporting both and we want to move away from the .commands format.

**Comment by rusenask** [comment]
I agree that the new .yaml format looks much better and it should be the default (and probably the only one format), however it looks like current users aren't aware that exported file format has changed. By exporting both formats we can create a non painful way for transition - without modifying existing scripts that control test processes.

**Comment by JohnFDavenport** [comment]
I spoke to @johnecobo  about this and agreed that we need both formats. Without any documentation on the new format we can't roll it out because 1,200 complex test scenarios exist and the users do modify the exports. They are in the middle of a major programme that will increase the number of scenarios to 3,000 within the next few months. Once it is available we can start discussions with users, show the benefits and discuss a progressive cut-over.

**Comment by rusenask** [comment]
What kind of documentation you require? 
http://stubo-app.readthedocs.org/en/latest/pages/commands.html#command-file-yaml
Is this not enough?

**Comment by erowan** [comment]
yes but do we need to export both?

**Comment by JohnFDavenport** [comment]
They need the current format. Bear in mind at least one project has parsed the command files to add SOAP headers to an existing set of stubs. Our users are self-sufficient and resourceful. They automate many things and their use of Stubo is sometimes surprising.

The documentation looks good but we need to see user feedback next. I've suggested  a few minor spelling corrections.

**Comment by JohnFDavenport** [comment]
@erowan deprecating outdated features and allowing an orderly migration would be acceptable.

**Comment by erowan** [comment]
I suggested adding a new url argument to specify the export format. This could be added to the manage page with another action => export scenario (YAML)
                                                                                                                                                                                                                   export scenario  (.commands)
On 6 Jul 2015, at 16:56, John Davenport <notifications@github.com> wrote:

> @erowan deprecating outdated features and allowing an orderly migration would be acceptable.
> 
> —
> Reply to this email directly or view it on GitHub.
>

**Pull request merged**
